### ISSUE TITLE
Event loop is closed / Bunkr Uploader, not uploading

### ISSUE THREAD

**Issue by traydays** [alexmi256/bunkrr-uploader#1]
Bunkr Uploader is no longer working as intended. It keeps throwing an error about 'id' and also saying the file/album name already in use. When the file is 100% not in the album. 

`DEBUG:bunkrr_uploader.bunkrr_uploader:{'chunkSize': {'default': '25MB', 'max': '95MB', 'timeout': 1800000},
 'defaultTemporaryUploadAge': 0,
 'enableUserAccounts': True,
 'fileIdentifierLength': {'default': 8, 'force': False, 'max': 32, 'min': 4},
 'maxSize': '2000MB',
 'private': True,
 'stripTags': {'blacklistExtensions': ['.gif'],
               'default': False,
               'force': False,
               'video': False},
 'temporaryUploadAges': [0]}
DEBUG:bunkrr_uploader.bunkrr_uploader:created_folder response: {'description': 'Album name already in use.', 'success': False}
ERROR:bunkrr_uploader.bunkrr_uploader:Error: 'id' key is missing in the created_folder dictionary: {'description': 'Album name already in use.', 'success': False}
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E5F603CDC0>
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed`

**Comment by cretuemanuel** [comment]
https://github.com/alexmi256/bunkrr-uploader/blob/573d6054118c88c4e0de3ece91cbb3ab6e7238fe/src/bunkrr_uploader/__init__.py#L1
